name: fic_mini_project
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  shared_preferences: ^2.1.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+1
  intl: ^0.17.0
  sqflite: ^2.2.6
  qr_flutter: ^4.0.0
  carousel_slider: ^4.2.1
  mobile_scanner: ^3.2.0
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/success_order.png
    - assets/banner_promo/

flutter_icons:
  android: true
  image_path: 'assets/logo/logo.png'
  adaptive_icon_background: 'assets/logo/background.png'
  adaptive_icon_foreground: 'assets/logo/foreground.png'
