name: fic_mini_project
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  sqflite: ^2.3.0
  qr_flutter: ^4.1.0
  carousel_slider: ^4.2.1
  mobile_scanner: ^3.5.2
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/success_order.png
    - assets/banner_promo/

flutter_icons:
  android: true
  image_path: 'assets/logo/logo.png'
  adaptive_icon_background: 'assets/logo/background.png'
  adaptive_icon_foreground: 'assets/logo/foreground.png'
